development:
  adapter: mysql
  database: boradois_development
  username: iuri
  password:
  host: localhost

test:
  adapter: mysql
  database: boradois_test
  username: iuri
  password:
  host: localhost

production:
  adapter: mysql
  database: boradois_production
  username: production
  password: qualquer
  host: localhost
