development:
  adapter: mysql
  database: boradois_development
  username:
  password:
  host: localhost

test:
  adapter: mysql
  database: boradois_test
  username:
  password:
  host: localhost

production:
  adapter: mysql
  database: boradois_production
  username: production
  password: qualquer
  host: localhost
