development:
  adapter: mysql
  database: boradois_development
  username: root
  password:
  host: localhost

test:
  adapter: mysql
  database: boradois_test
  username: root
  password:
  host: localhost

production:
  adapter: mysql
  database: boradois_production
  username: root
  password: 
  host: localhost
